---

aws_tag_environment: "Production"

aws_name_prefix: hub-prod-

aws_cidr_block: 10.10.0.0/16
aws_region: us-east-1
aws_access_key: "{{ vault_aws_access_key }}"
aws_secret_key: "{{ vault_aws_secret_key }}"

aws_s3_bucket_name: "lightster-hub-prod"
aws_s3_bucket_prefix: "_site/"

aws_ssh_key_file: "~/.ssh/id_rsa.lightster-mbpr.pub"

aws_webauth_instance_type: t2.micro

aws_certificate_arn: "{{ vault_aws_certificate_arn }}"

aws_zones:
  us_east_1a:
    aws_zone: us-east-1a
    public_cidr: 10.10.100.0/24
    tag_suffix: "A"
  us_east_1b:
    aws_zone: us-east-1b
    public_cidr: 10.10.101.0/24
    tag_suffix: "B"
