---

- name: Check to see if oauth2_proxy is installed
  stat:
    path: /usr/bin/oauth2_proxy
  register: oauth2_proxy_exists

- name: Download oauth2_proxy archive
  get_url:
    url: https://github.com/bitly/oauth2_proxy/releases/download/v2.1/oauth2_proxy-2.1.linux-amd64.go1.6.tar.gz
    dest: /tmp/oauth2_proxy.tar.gz
  when: oauth2_proxy_exists.stat.exists == false
  become: true

- name: Unarchive oauth2_proxy archive
  # I don't use the 'unarchive' command here because it does not support
  # stripping directories on extraction
  command: >
    tar zxf /tmp/oauth2_proxy.tar.gz --strip-components 1 -C /usr/bin/
  when: oauth2_proxy_exists.stat.exists == false
  become: true

- name: Remove oauth2_proxy archive
  file:
    path: /tmp/oauth2_proxy.tar.gz
    state: absent
  become: true

- name: Define the directory to store the auth templates
  set_fact:
    auth_templates_dir: '/var/www/html/hub/auth'
  when: "{{ auth_templates_url != '' }}"

- name: Create directory for auth templates
  file:
    path: "{{ auth_templates_dir }}"
    state: directory
    recurse: true
  when: "{{ auth_templates_dir != '' }}"
  become: true

- name: Download auth templates
  get_url:
    url: "{{ auth_templates_url }}/{{ item }}"
    dest: "{{ auth_templates_dir }}/{{ item }}"
  when: "{{ auth_templates_url != '' }}"
  with_items:
    - sign_in.html
    - error.html
  become: true
  notify: reload supervisor

- name: Install oauth2_proxy config
  template:
    src: "oauth2_proxy.cfg.j2"
    dest: "/etc/oauth2_proxy.cfg"
    owner: nginx
    group: nginx
    mode: "0600"
  become: true
  notify: reload supervisor

- name: Make oauth2_proxy log directory
  file:
    path: "/var/log/oauth2_proxy"
    state: directory
    owner: nginx
    group: nginx
    mode: 0755
  become: true

- name: Install oauth2_proxy-hub supervisor config
  template:
    src: "supervisor/conf.d/oauth2_proxy-hub.conf.j2"
    dest: "/etc/supervisor/conf.d/oauth2_proxy-hub.conf"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: reload supervisor
